language: rust

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake gcc

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install cargo-tarpaulin
    fi
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      rustup component add clippy
    fi

script: # 集成脚本
  - cargo update
  - cargo check --all --all-features
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo clippy --all-targets --all-features
      cargo test --all-features --all
    fi

after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        taskset -c 0 cargo tarpaulin --out Xml --all --all-features
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"
    fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=

notifications:
  email:
    recipients:
      - i@hexilee.me
  on_success: change
  on_failure: always