language: rust
dist: trusty

rust:
  - stable
  - nightly

before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install cargo-tarpaulin
    fi
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      rustup component add clippy
    fi

script: # 集成脚本
  - cargo update
  - cargo check --all --all-features
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo clippy --all-targets --all-features
      cargo test --all-features --all
    fi

after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        taskset -c 0 cargo tarpaulin --out Xml --all --all-features
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"
    fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=
    - OPENSSL_VERSION=openssl-1.0.2

notifications:
  email:
    recipients:
      - i@hexilee.me
  on_success: change
  on_failure: always