[package]
name = "roa"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/Hexilee/roa"
documentation = "https://docs.rs/roa"
homepage = "https://github.com/Hexilee/roa"
description = """
async web framework inspired by koajs, lightweight but powerful.
"""
keywords = ["http", "web", "framework", "async"]
categories = ["network-programming", "asynchronous",
              "web-programming::http-server"]
exclude = [".travis.yml", "*.sh"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "roa-core",
    "roa-proc-macro",
    "roa-forward",
    "roa-cors",
]

[badges]
travis-ci = { repository = "Hexilee/roa" }

[dependencies]
http = "0.2"
log = "0.4"
futures = "0.3"
async-std = "1.4"
bytesize = "1.0"
roa-core = {path = "./roa-core", version = "0.1"}
url = { version = "2.1.1", optional = true }
async-trait = { version = "0.1.22", optional = true }
cookie = { version = "0.12", features = ["percent-encode"], optional = true }
percent-encoding = { version = "2.1", optional = true }
jsonwebtoken = { version = "6", optional = true }
serde = { version = "1", optional = true }
mime = { version = "0.3", optional = true }
askama = { version = "0.9", optional = true }
serde_json = { version = "1.0", optional = true }
serde_urlencoded = { version = "0.6", optional = true }
encoding = { version = "0.2", optional = true }
mime_guess = { version = "2.0", optional = true }
radix_trie = { version = "0.1.6", optional = true }
regex = { version = "1.3", optional = true }

[dev-dependencies]
tokio = {version = "0.2", features = ["full"]}
async-std = "1.4"
pretty_env_logger = "0.3"
serde = {version = "1", features = ["derive"] }
test-case = "1.0.0"

[features]
default = ["query", "cookies", "router"]
full = ["default", "jwt", "body"]
query = ["url", "async-trait"]
cookies = ["async-trait", "cookie", "percent-encoding"]
jwt = ["async-trait", "jsonwebtoken", "serde"]
body = [
    "async-trait", 
    "percent-encoding", 
    "serde", 
    "mime", 
    "askama", 
    "serde_json", 
    "serde_urlencoded", 
    "encoding", 
    "mime_guess",
]
router = ["regex", "radix_trie", "percent-encoding", "async-trait"]

[package.metadata.docs.rs]
features = ["full"]

[[example]]
name = "serve-file"
path = "examples/serve-file.rs"
required-features = ["body"]
