[package]
name = "roa"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["roa-basic", "roa-core"]

[dependencies]
roa-core = {path = "./roa-core"}

[dev-dependencies]
tokio = {version = "0.2", features = ["full"]}
async-std = "1.4"
pretty_env_logger = "0.3"