[package]
name = "roa"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.13", features = ["stream"] }
futures = "0.3"
bytes = "0.5"
http = "0.2"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
