[package]
name = "roa-root"
version = "0.5.0-alpha"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"
license = "MIT"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "roa",
    "roa-core",
    "roa-diesel",
    "roa-body",
    "integration/diesel-example",
    "integration/multipart-example"
]

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
reqwest = { version = "0.10", features = ["json", "cookies", "gzip"] }
async-std = { version = "1.4", features = ["attributes"] }
pretty_env_logger = "0.3"
serde = { version = "1", features = ["derive"] }
test-case = "1.0.0"
roa = { path = "./roa", features = ["full"] }

[[example]]
name = "serve-file"
path = "examples/serve-file.rs"
required-features = ["body", "compress", "router"]

[[example]]
name = "hello-world"
path = "examples/hello-world.rs"

[[example]]
name = "restful-api"
path = "examples/restful-api.rs"

[[test]]
name = "serve-file"
path = "tests/serve-file.rs"

[[test]]
name = "restful"
path = "tests/restful.rs"
