[package]
name = "roa"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["roa-middlewares"]

[dependencies]
futures = "0.3"
bytes = "0.5"
http = "0.2"
async-std = { version = "1.4", features = ["attributes"] }
log = "0.4"
hyper = "0.13"
