[package]
name = "roa-core"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
bytes = "0.5"
http = "0.2"
log = "0.4"
hyper = "0.13"

[dev-dependencies]
tokio = {version = "0.2", features = ["full"]}
async-std = "1.4"
pretty_env_logger = "0.3"
