[package]
name = "roa-core"
version = "0.5.0-alpha"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/Hexilee/roa"
documentation = "https://docs.rs/roa-core"
homepage = "https://github.com/Hexilee/roa"
description = "core components of roa web framework"
keywords = ["http", "web", "framework", "async"]
categories = ["network-programming", "asynchronous",
              "web-programming::http-server"]



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
travis-ci = { repository = "Hexilee/roa" }

[dependencies]
futures = "0.3"
bytes = "0.5"
http = "0.2"
hyper = { version = "0.13", default-features = false, features = ["stream"] }
async-std = "1.5.0"
futures-timer = "3.0"
log = "0.4"
tokio = "0.2"
async-trait = "0.1.24"

[dev-dependencies]
pretty_env_logger = "0.3"
async-std = { version = "1.5.0", features = ["attributes"] }
tokio = {version = "0.2", features = ["full"]}
reqwest = { version = "0.10", features = ["json"] }

[features]
runtime = []
