[package]
name = "roa-router"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roa-core = { path = "../roa-core", version = "0.1" }
http = "0.2"
percent-encoding = "2.1"



[dev-dependencies]
test-case = "1.0.0"
