[package]
name = "multipart-example"
version = "0.1.0"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roa = { path = "../../roa", features = ["router", "body"] }
roa-multipart = { path = "../../roa-multipart" }
tokio = { version = "0.2.13", features = ["rt-threaded", "blocking", "macros"] }
log = "0.4"
pretty_env_logger = "0.3"
futures = "0.3"
