[package]
name = "roa-tls"
version = "0.5.0-alpha"
authors = ["Hexilee <hexileee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roa-core = { path = "../roa-core", version = "0.5.0-alpha" }
roa-tcp = { path = "../roa-tcp", version = "0.5.0-alpha" }
futures = "0.3"
rustls = "0.16.0"
async-tls = "0.6.0"
async-std = "1.5.0"

[dev-dependencies]
reqwest = { version = "0.10", features = ["rustls-tls"] }
async-std = "1.5.0"
tokio = { version = "0.2", features = ["full"] }
roa-core = { path = "../roa-core", version = "0.5.0-alpha", features = ["runtime"] }

